[project]
name = "health-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "streamlit",
    "openai-agents>=0.2.11",
]

[tool.setuptools]
packages = ["agent_s", "guardrails", "tools"]
